# Format: https://dart.dev/tools/pub/pubspec

name: mansion
description: A stately library for crafting and deciphering ANSI escape codes.
version: 0.1.0

environment:
  sdk: ^3.4.0

repository: https://github.com/matanlurey/mansion

dependencies:
  meta: ^1.15.0

dev_dependencies:
  args: ^2.5.0
  benchmark_harness: ^2.2.2
  checks: ^0.3.0
  coverage: ^1.8.0
  oath: ^0.2.0
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_static: ^1.1.2
  test: ^1.25.7
