# Format: https://dart.dev/tools/pub/pubspec

name: mirage
description: |-
  Generate noise and patterns algorithmically for use in software, textures, and
  graphics.
short_description: Noise and pattern generation.

version: 0.2.0+1

homepage: https://github.com/matanlurey/pub.lurey.dev/tree/main/packages/mirage
issue_tracker: https://github.com/matanlurey/pub.lurey.dev/labels/pkg-mirage

resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  chaos: ^0.1.1
  meta: ^1.14.0

dev_dependencies:
  checks: ^0.3.0
  image: ^4.2.0
  oath: ^0.2.0
  path: ^1.9.0
  test: ^1.25.3
