# Format: https://dart.dev/tools/pub/pubspec

name: lore

description: |-
  Fast, structured, and idiomatic logging with an extensible API.
version: 0.1.0-dev

homepage: https://github.com/pub.lurey.dev/tree/main/packages/lore
issue_tracker: https://github.com/matanlurey/pub.lurey.dev/labels/pkg-lore

environment:
  sdk: ^3.5.0

dependencies:
  meta: ^1.15.0

dev_dependencies:
  checks: ^0.3.0
  oath: ^0.2.1
  test: ^1.25.7
